### ISSUE TITLE
Cannot View In Browser

### ISSUE THREAD

**Issue by dekakast** [lynn/hello-wordl#116]
- I can view locally on my laptop. 
- I then compiled successfully on my server but cannot view in browser. 
- I also confirmed that I changed the "homepage" key in package.json to my domain name. 

Appreciate any suggestions.

**Comment by wordlverse** [comment]
Forgot to mention that I also enabled port 3000, but still cannot access https://mydomain.com:3000

**Comment by dekakast** [comment]
123.456.789.012:3000 works but I cannot get domain.com:3000 to work

**Comment by dekakast** [comment]
fixed
