### ISSUE TITLE
Multiple Today's Words

### ISSUE THREAD

**Issue by dekakast** [lynn/hello-wordl#118]
I don't understand the purpose of "Today's Word." If you solve it, you can go ahead and play again and there is a new Today's Word. It defeats the purpose of a unique Today Word.  "Today's Word" is really no different than the Random setting. Maybe I am missing something.

**Comment by lynn** [comment]
Hi! How it works is that everybody gets the same _sequence_ of words in "Today's" mode, for that day. So if you and your friend want to play 3 words each day, you can both play 3 games in "Today's" mode and get the same words.

"Random" is still useful if you access the game twice a day from different devices and don't want to play all the same words.
