### ISSUE TITLE
defacto

### ISSUE THREAD

**Issue by nativecranberry** [lynn/hello-wordl#122]
Hellowordl says "defacto" is not a valid word.  Why not?

**Comment by lynn** [comment]
I believe _de facto_ is standardly two words, and I guess the Scrabble dictionary agrees.

**Comment by nativecranberry** [comment]
Hello Again,

hello wordle is telling me "forgerer" is not a word, but it is in the
dictionary.  A person who forges.

All the best.

Jeffrey Reel
