### ISSUE TITLE
Feature Request - Share Challenge

### ISSUE THREAD

**Issue by owarij** [lynn/hello-wordl#14]
Submitting a feature request if possible where you can hit a share button and generate a link to the current word challenge you just did. 
That way, I can send it to friends and family if I felt like a specific work was a really nice challenge.

**Comment by mayukhnair** [comment]
While the button gets added, there is a way: share the URL with any random number added to the `seed` parameter.

e.g. http://foldr.moe/hello-wordl/?seed=426

**Comment by lynn** [comment]
This sounds like a fun feature! I've thought of adding a button that copies something like this to the clipboard:

> hello wordl 4/6  
> ⚪⚪⚪🟡⚪  
> 🟢🟡⚪⚪🟡  
> 🟢⚪🟢🟢⚪  
> 🟢🟢🟢🟢🟢  
> https://foldr.moe/hello-wordl/?challenge=Y3J5cHQ

But maybe it feels a bit derivative and/or obnoxious, and just the `?challenge` link bit is enough 😅

**Comment by lynn** [comment]
I added a "challenge a friend to this word" button. Let me know if it's working as expected!
