### ISSUE TITLE
Inconsistent proper noun inclusion and American bias

### ISSUE THREAD

**Issue by Jeanfeels** [lynn/hello-wordl#16]
![Screenshot_20220112-105739_Chrome](https://user-images.githubusercontent.com/61132755/149056101-9a3e65eb-e94d-427c-a921-58f32bdc09c4.jpg)
Above: One of many, many examples.  

I also want to note that it would be nice to have a separate option for british spelling (colour, armour, favourite, aluminium etc) though it might be a bit challenging to implement that given the sheer number of edge cases.

**Comment by stonedbovines** [comment]
'boston' is also a card game

[boston: collins dictionary](https://www.collinsdictionary.com/dictionary/english/boston)

**Comment by lynn** [comment]
Thanks for the report! As @stonedbovines points out, some proper nouns have a more obscure meaning as an… improper(?) noun, and _boston_ is apparently one of those.

I try to eliminate these from the target word list, but I won't eliminate them as guesses.

For now, the only language available is US English. I will probably treat support for British spellings the same way I treat support for other languages, which is something I'm interested in going forward, though maintaining the word lists sounds like a bit of a pain.
