### ISSUE TITLE
Add indication of duplicate letters

### ISSUE THREAD

**Issue by Jeanfeels** [lynn/hello-wordl#17]
There are a lot of words with two or more of a single letter, but no way to indicate (especially vital for longer word games) that a letter appears more than once.

I propose a third colour code, blue would be ideal, that appears only if a letter is in a valid spot but there are more of that letter to be located. 

I don't think you'd need to or want to change the colours of misplaced letters due to how much easier it might make short games, but if you did I'd probably suggest orange for the hint colour. 

Here's a couple of mocked up examples, two of just blue and one for comparison with orange as well. 

Again, I am not sure it's a good idea to give away this information until a duplicate letter is correctly placed, so the orange tiles are not strictly needed and I'm just including it for the sake of comparison.

![sketch-1641960395455](https://user-images.githubusercontent.com/61132755/149062914-a5ea79f8-61ed-4850-9a08-12ca26a95d26.png)
![sketch-1641960339521](https://user-images.githubusercontent.com/61132755/149062916-cf099601-6b29-4ab5-a962-08c9594938cc.png)
![sketch-1641960842027](https://user-images.githubusercontent.com/61132755/149062911-9f3fd318-6a3b-49dd-b78c-e4f630d235a5.png)

**Comment by mcdowell7** [comment]
I wonder if removing words with duplicate letters from the game dictionary is possible. I don't know how much this would reduce the number of potential solutions for larger words but it would avoid the need for new colours and make the game more elegant in my opion

**Comment by lynn** [comment]
Hmm, sorry, I think it's fine as-is. I know duplicate letters are controversial, but Wordle has them too, and clues them the same way I do, so I don't really intend to change it. I think it keeps the game challenging and otherwise it would get a bit too easy to win every time.
