### ISSUE TITLE
Add hard mode

### ISSUE THREAD

**Issue by passcod** [lynn/hello-wordl#2]
Like Wordle, "hard" mode enforces that the present/correct colour hints are respected in subsequent guesses. Unlike Wordle it would be nice if this version enforced the "must not place letter in same place if given yellow hint" constraint.

**Comment by lynn** [comment]
Next on my TODO list 🙂

**Comment by lynn** [comment]
It's in! https://twitter.com/chordbug/status/1483205542780850176

**Comment by passcod** [comment]
Ah, thank you!

It doesn't enforce the Yellows, though, not even "must contain X" like Wordle does

![Screenshot_20220118-113620.jpg](https://user-images.githubusercontent.com/155787/149844312-e3c647c3-f8ff-4ea4-bb1d-a1e907385084.jpg)

At NAGGY it should have told me that P must be present, for example
