### ISSUE TITLE
how come this word is not accepted ?

### ISSUE THREAD

**Issue by duhuhsoso** [lynn/hello-wordl#20]
It says 'muslim' is not a word !

**Comment by lynn** [comment]
Hiya, sorry about this. I use an [official Scrabble tournament word list](https://en.wikipedia.org/wiki/NASPA_Word_List) to validate guesses, but Scrabble disallows playing proper nouns, and _Muslim_ is written with a capital M in English. (_Buddhist_ is not allowed either, or even _Tuesday_.)

I don't think Wordle benefits as much as Scrabble from a rule that disallows guessing proper nouns, especially if they are so common. But for now, I think sticking to _some_ official word list is better than _me_ being the ultimate case-by-case judge of what is and isn't a valid English word (which I certainly don't have the time to do). I hope you understand.

If I find a trustworthy dictionary that includes very normal words like _Muslim_ and _Tuesday_, I will gladly switch to it! (Maybe [`words`](https://en.wikipedia.org/wiki/Words_(Unix)) isn't so bad? Hmm, I will look into that.)
