### ISSUE TITLE
Colorblind options

### ISSUE THREAD

**Issue by n5mashni** [lynn/hello-wordl#21]
Would be cool to include a pattern in addition to the yellow/green/grey options, that way it eliminates any issues for folx who are colorblind.

**Comment by lynn** [comment]
Hello! The little solid and dotted borders around green and yellow clues are to aid colorblind players, eliminating the need for a second set of colors. :tada: 

![image](https://user-images.githubusercontent.com/16232127/149680342-b574ebd4-e53a-454b-8e0c-de712bd35d26.png)

(I've been considering making them 1px thicker, so maybe I'll play around with that.)

**Comment by n5mashni** [comment]
I did not notice that!  Well done!  Thanks for the response.
