### ISSUE TITLE
why is ''April'' not a valid word?

### ISSUE THREAD

**Issue by Zack113draws** [lynn/hello-wordl#22]
come on now, we all know April is the forth month of the year and should definitely be a valid word.
![Screenshot_20220114-174023_Brave](https://user-images.githubusercontent.com/97731649/149495483-ca6491b4-e247-4397-8d45-0a5a22742bfd.jpg)

**Comment by mregamr** [comment]
If I had to guess, I'd say that proper names are not allowed

**Comment by lynn** [comment]
I use a Scrabble word list to verify guesses, and I suppose it indeed considers April a proper noun, even though I agree that that's a little strange to think about. I've been surprised by it not permitting _Tuesday_, either.

Currently, the official Wordle game doesn't allow it, either, so I won't currently consider this a bug:

![image](https://user-images.githubusercontent.com/16232127/149680231-7c0135b4-4d21-46ec-b713-a19e6a8169fb.png)
