### ISSUE TITLE
Suggestion: Display Word Count

### ISSUE THREAD

**Issue by mregamr** [lynn/hello-wordl#23]
I would really enjoy seeing a count of the words that are possible with the current guess (after it's resolved).  I don't believe it would spoil anything.

For instance, I guessed a word with yellow L in the middle, the other letters were not in the word.  I would love to see how many words have an L that's not in that position.

If that's not desirable, it would still be interesting information after solving (or not) the puzzle.

Thanks,
Tom

**Comment by lynn** [comment]
I'm not so interested in adding this feature currently. Maybe you can suggest this feature to [Unwordle](https://sadmoody.github.io/unwordle/) (also [on GitHub](https://github.com/sadmoody/unwordle-svelte)). Thanks for the suggestion!
