### ISSUE TITLE
duplicate letter coloring

### ISSUE THREAD

**Issue by TeegardenMath** [lynn/hello-wordl#25]
Right now, if a letter appears N times in the answer and more than N times in a guess, only the first N appearances of the letter are colored. 

For instance, in the screenshot below, the answer is HANDWRITTEN. When I guess the word ATTRACTIONS, it colors the first two Ts yellow (because there are two Ts in HANDWRITTEN) and leaves the third one gray.

<img width="538" alt="Screen Shot 2022-01-14 at 12 00 05 PM" src="https://user-images.githubusercontent.com/72769325/149577498-f185db1f-14f8-4d2f-8f97-5cad8c9c5066.png">

This isn't, to my understanding, proper Mastermind-style feedback. All three Ts should be colored yellow, to indicate that there are Ts in the answer, but not in those locations. This way gives too much information.

**Comment by lynn** [comment]
This is how Wordle works. Watch what happens when I locally hack today's target word to be "STEEP" and then guess "EERIE":

![image](https://user-images.githubusercontent.com/16232127/149680099-1aa11973-beac-413f-934a-46d193d60563.png)

Only as many E's as are in the target word light up yellow.
