### ISSUE TITLE
Letters now have scrollbars (desktop, chrome)

### ISSUE THREAD

**Issue by cburschka** [lynn/hello-wordl#27]
This is pretty recent, so I'm suspecting the last CSS commit an hour ago might've done it.
![image](https://user-images.githubusercontent.com/1448001/149636501-08803202-69ab-4eae-8e2c-3a60cbc470b9.png)

Mobile browsers seems unaffected; I haven't checked other desktop browsers.

**Comment by arancaytar** [comment]
![image](https://user-images.githubusercontent.com/36588490/149636740-3fb55f62-f9e3-4936-aa8e-7c111ab02c98.png)
Goes away if I uncheck the `.Row-letter { overflow: overlay; }` directive.

**Comment by lynn** [comment]
This was a failed experiment for making the grid look nice on very, very narrow screens (in 11-letter mode and such). I've reverted it now, but feel free to reopen if you're still seeing this!
