### ISSUE TITLE
Backspace triggers browser history

### ISSUE THREAD

**Issue by leahneukirchen** [lynn/hello-wordl#29]
I use Backspace to return to the previous page in my browser, but when I press Backspace in Hello Wordl, this should not happen of course.  I think adding `e.preventDefault()` to
https://github.com/lynn/hello-wordl/blob/47a7782b8fb8590a6c400e037eac02c87c7e8504/src/Game.tsx#L97
should fix this.

**Comment by lynn** [comment]
I pushed a hopeful fix in 81555b938df3f74610ce255485502c0c00259c46. If the issue is still there, feel free to reopen. Thanks for reporting!

**Comment by leahneukirchen** [comment]
Works great!
