### ISSUE TITLE
Edge case with presence hint and repeated letters

### ISSUE THREAD

**Issue by passcod** [lynn/hello-wordl#3]
![Screenshot_20220103-145701.jpg](https://user-images.githubusercontent.com/155787/147895212-4e68040c-d880-4192-9233-f2a1a8e24b32.jpg)

In this example, should the second I in the LIMITS guess also be yellow?

**Comment by nhamovitz** [comment]
IMO, no — because the first `I` is yellow and the second one isn't, you know that there's only one `I` in the word. This way you're rewarded for guessing words with repeated letters in them, to check if they're repeated in the answer. I believe that Wordle has the same behavior.
