### ISSUE TITLE
androgenous not found in word list

### ISSUE THREAD

**Issue by bennywwg** [lynn/hello-wordl#36]

**Comment by roryokane** [comment]
Are you sure you’re not thinking of the word “[androgynous](https://www.merriam-webster.com/dictionary/androgynous)”?

Most online dictionaries I checked didn’t have the word “androgenous”. The only dictionary I found that had it was [Wiktionary](https://en.wiktionary.org/wiki/androgenous), which defines it as either a synonym for “androgenic” or a misspelling of “androgynous”.

**Comment by bennywwg** [comment]
You're correct. I was thinking of androgynous.
