### ISSUE TITLE
Static resources 404 on http://foldr.moe/hello-wordl/

### ISSUE THREAD

**Issue by NoahCarnahan** [lynn/hello-wordl#37]
Thanks for creating this implementation of the game!

Unfortunately, the game currently won't load for me on http://foldr.moe/hello-wordl/
I get the following in my browser console:
```
GET http://foldr.moe/static/js/main.f1c0bd93.js net::ERR_ABORTED 404 (Not Found)
GET http://foldr.moe/static/css/main.b2fee078.css net::ERR_ABORTED 404 (Not Found)
```

**Comment by lynn** [comment]
I am working right now on moving the game to http://hellowordl.net (and ASAP to https://hellowordl.net but this is yet another challenge). It might take up to 24 hours for things to settle down.

**Comment by NoahCarnahan** [comment]
ok good to know! Glad you're already aware.

**Comment by lynn** [comment]
HTTPS seems to be working now :+1:
