### ISSUE TITLE
plural nouns ending in s should not be allowed as answers

### ISSUE THREAD

**Issue by psymar** [lynn/hello-wordl#40]
Wordle allows them as guesses, but not answers.

**Comment by lynn** [comment]
I eliminated most of them in 54f3c98bff522ef04f17144cc55b93067b422082, using a software library to detect plurals and conjugated verbs. It's not 100% accurate, however, and I know some plurals have slipped through the cracks. Can you tell me which plurals you ran into? I will gladly delete them from the targets list.

**Comment by psymar** [comment]
There are quite a lot, honestly.  Here are the first 39 I see in the list, because going through this list is tedious and it should give you some idea; I'd estimate there are several hundred left, although I can probably scrape the rest with a script and then verify by hand.

terms
conditions
eyes
hands
services
effects
parts
values
hours
ways
relations
laws
elements
arms
rates
names
affairs
operations
acts
steps
sales
fields
details
troops
feelings
banks
provisions
funds
arts
windows
proceedings
contents
waters
grounds
wages
statistics
rooms
assets

**Comment by lynn** [comment]
Thank you! I gave programmatically eliminating them another shot (using "WordNetLemmatizer" now instead of "morphy": https://stackoverflow.com/questions/31016540/lemmatize-plural-nouns-using-nltk-and-wordnet) and it found a bunch more, though still probably not all of them.
