### ISSUE TITLE
Objectionable words

### ISSUE THREAD

**Issue by Onalee33** [lynn/hello-wordl#41]
The answer to the puzzle I just did was "bitch." And then the very next puzzle, the answer was "whore."  I would suggest removal of those words from the source list, as well as a brainstorming session to think of others that should probably be removed.

**Comment by lynn** [comment]
Hi, thanks for the report! I've removed these two words, along with some other rare/medical/science terminology. Tidying up the word list is a constant effort — feel free to look at the list and report any more inappropriate entries: https://github.com/lynn/hello-wordl/blob/main/src/targets.json
