### ISSUE TITLE
Can't challenge friends to uncommon words

### ISSUE THREAD

**Issue by ashastral** [lynn/hello-wordl#42]
I wanted to be clever and encode my own challenges in the URL, but some of them give me the "Invalid challenge string" error because they are rarer than "murky":

https://github.com/lynn/hello-wordl/blob/6583be1968dd3c71f35581569f7bb4599048fd3d/src/Game.tsx#L41

I think replacing `targets` with `targetList` here would enable this use case. Does this seem like a reasonable change?

**Comment by lynn** [comment]
Fixed! You can actually use any dictionary word now: http://hellowordl.net/?challenge=enl6enl2YXM

**Comment by ashastral** [comment]
Thank you!
