### ISSUE TITLE
Enhancement request: add login

### ISSUE THREAD

**Issue by issakov** [lynn/hello-wordl#46]
It would be nice to be able to login—perhaps thru a 3rd party like Google, Apple or FB—so your record is retained across devices.

**Comment by carpiediem** [comment]
record?

**Comment by lynn** [comment]
Hello! Sorry, I am interested in neither record-keeping (see #18) nor account-linking or even having any notion of "hello wordl accounts". (Mostly for the same reason you don't "log in" to a Rubik's cube or a deck of cards.)
