### ISSUE TITLE
Challenges can be easily abused to make impossible words

### ISSUE THREAD

**Issue by RubyPiec** [lynn/hello-wordl#47]
Take these 2 links for example: 
https://hellowordl.net/?challenge=dW5jb3B5cmlnaHRhYmxl 
https://hellowordl.net/?challenge=YmU=

When you open them, you immediately notice something is wrong about them, they have an unusual amount of letters (first link has 15, second one has 2), 

This is because challenge links are in base64 which you can easily decode text in and encode text in using https://www.base64encode.org/
I recommend either not using base64 OR just making this impossible all together. Unless this is an intended feature, in which case sorry for making this so pointlessly long.

**Comment by lynn** [comment]
I don't mind friends pranking friends with base64-trickery (I think it's kind of a fun accidental feature), but I'm worried about the app crashing after hitting Enter after the 2-letter game here. 🤔

**Comment by carpiediem** [comment]
Reset the word counter to the usual range before starting a new game?

**Comment by lynn** [comment]
Pushed a fix!
