### ISSUE TITLE
Challenge a friend to this word ios 

### ISSUE THREAD

**Issue by dskunkler** [lynn/hello-wordl#48]
Currently: When the button is pressed a url is generated. However, the user is unable to interact with the text generated.

Desired functionality: should either copy url to clipboard on button press or text should be able to be highlighted and copied. Of the two I think the first would be best for everyone.

**Comment by lynn** [comment]
Oops, I've made the link copyable now (aba632ed13d659c9bd82142114ec4a586e10e063 🤦 🙂 ), but I will look further into why "copy to clipboard" isn't working in the first place in iOS. The link being displayed for manual copying is only meant to be "fallback" behavior when writing to the clipboard fails.

**Comment by dskunkler** [comment]
@lynn You're solution seems to have fixed the copy to clipboard, or at least my phones letting me now on button press. Marking as resolved.
