### ISSUE TITLE
Remove plurals

### ISSUE THREAD

**Issue by ogregoire** [lynn/hello-wordl#5]
Plurals are no fun because you don't guess only 5-letters words, but also 4-letters words with plurals. 

The word list of Wordle doens't include plural words, while with your version at the moment when I try, 1 in every 3 hidden word is a plural word.

So please remove plural words, or at least groom the entry list. (Note, not every word that ends with an 's' is a plural.)

**Comment by lynn** [comment]
This has been on my mind lately, and I do think it's "fresher" if I remove plurals and inflected verbs. At the same time, I've thought that it's strange that this is an unwritten rule in Wordle. Maybe I will write it into the rules in my game, if I get around to it.

(Note to self: I might be able to use an NLP library to figure out which words to eliminate 🤔 )

**Comment by lynn** [comment]
I used NLTK to recognize and remove a kajillion plural forms and verb conjugations in 54f3c98bff522ef04f17144cc55b93067b422082. This means fewer possible targets, but I think they are more fun/interesting on average! It also isn't 100% accurate so I'll keep an eye out for them manually from now on.
