### ISSUE TITLE
Feature request: Share results

### ISSUE THREAD

**Issue by ebolot** [lynn/hello-wordl#50]
Wordle has the ability to share results, e.g. see below.

 can't do the same with one click in Hello Wordl, which is sad.

 
Wordle 216 3/6

⬛⬛⬛🟨🟨
🟩⬛🟩⬛⬛
🟩🟩🟩🟩🟩

**Comment by lynn** [comment]
I'm rolling out a "copy result as emoji" button.

<img src="https://user-images.githubusercontent.com/16232127/150781936-19203eb0-4c03-42f8-aa82-3d1ce4c48f2b.png" alt="screenshot of the new button" width="400" >

It copies something like this:

> https://hellowordl.net/?challenge=bG9jYWw
> 
> ⬛⬛🟨⬛⬛
> ⬛🟨⬛⬛⬛
> 🟨⬛⬛⬛🟨
> 🟨🟩⬛⬛🟨
> 🟩🟩🟩🟩🟩

**Comment by ebolot** [comment]
perfect, thanks!
