### ISSUE TITLE
Google Analytics without Cookies (or GDPR rules)

### ISSUE THREAD

**Issue by carpiediem** [lynn/hello-wordl#52]
[This](https://helgeklein.com/blog/google-analytics-cookieless-tracking-without-gdpr-consent/) might be a solution for you. I for one would be interested in some stats on most-guessed words, etc.

**Comment by lynn** [comment]
A Twitter user recommended [GoatCounter](https://www.goatcounter.com/) and I've been happy with the trimmed-down analytics I get from that. I mostly just want to know how many people are playing each day, and when. Thanks anyway!
