### ISSUE TITLE
Feature Request: Color Blind Mode

### ISSUE THREAD

**Issue by lmillersims** [lynn/hello-wordl#59]
Please add a color-blind mode, as in the original.

**Comment by thornae** [comment]
Looks like Wordle uses #85c0f9 for yellow and #f5793a for green in high contrast mode.

**Comment by Traupmann** [comment]
Please please add color-blind mode.  Very difficult to see immovable from unusable!

**Comment by khlsvr** [comment]
fwiw, there is a finnish and a lojban clone of wordle that supports color blind mode. Maybe its code can be used to implement it here, or maybe someone wants to create an english clone out of that one. The clones are called sanuli and valsr. I mentioned them in this issue https://github.com/lynn/hello-wordl/issues/18
