### ISSUE TITLE
Update to ReadMe

### ISSUE THREAD

**Issue by beepbeepboop** [lynn/hello-wordl#60]
Hi,

I'm currently trying to play around with the clone you've made but since I've never used TypeScript or CSS I'm having trouble figuring out how to run the code on my PC. 

Would it be possible to add some info to the ReadMe on how to run the code so that people can easily test it and play around with the code you wrote?

**Comment by JohnHKoh** [comment]
`npm install` then `npm start`, assuming you have Node.js and npm installed.

+1 for adding that to the README.
