### ISSUE TITLE
Feature Request: Show Dvorak and Colemak keyboard layouts

### ISSUE THREAD

**Issue by atoponce** [lynn/hello-wordl#67]
As a Dvorak typist, it would be nice to see the Dvorak layout beneath the puzzle instead of Qwerty. This could be a setting toggle.

![qwerty-dvorak-colemak](https://user-images.githubusercontent.com/699572/151406358-99474dcd-030a-404e-bd4d-415fa3fbe470.png)

**Comment by lynn** [comment]
I added some options!

![image](https://user-images.githubusercontent.com/16232127/151453446-1819d598-86d6-43f2-a93e-877ff0ab18d4.png)

**Comment by atoponce** [comment]
Nice! Thanks!
