### ISSUE TITLE
Feature Request: Add more wrong letter colours for cases where a letter is repeated twice

### ISSUE THREAD

**Issue by InfernoZXV** [lynn/hello-wordl#68]
As far as I know, in the original Wordle, words that have more than 1 of the same letter are excluded. However, in hello wordl, there are words that have repeated letters, which can make it highly confusing. Perhaps there could be a couple more colours added to the grey, green, and yellow to signify different things, such as:
Red: Right letter, wrong place, wrong quantity, such as guessing 'bowl' when the word is 'oboe'
Orange: Right letter, wrong place, right quantity, such as guessing 'anon' when the word is 'nine'
Lime: Right letter, right place, wrong quantity, such as guessing 'tree' when the word is 'core'
Perhaps this could be an option in the settings tab as to not confuse new players.

**Comment by lynn** [comment]
> As far as I know, in the original Wordle, words that have more than 1 of the same letter are excluded.

This isn't true (in recent memory: ABBEY, FERRY).

For more clue colors, see #17: I'm not interested in adding this, sorry. I think it's overwhelming and aesthetically unpleasant and makes the game too easy once you do tangle through the extra information.
