### ISSUE TITLE
Bug? Second instance of wrong-placed letter A is not yellow

### ISSUE THREAD

**Issue by final-wave** [lynn/hello-wordl#71]
Seems to me that the second "A" in BALSA should be yellow.

The puzzle was FLOAT.

![Clip 005031 FF 1740  hello wordl — Mozilla Firefox](https://user-images.githubusercontent.com/46074977/151616118-f6db39b2-2266-4ca3-a9af-7f5802981c90.png)

**Comment by lynn** [comment]
This is working as intended: the second A being grayed out means that there is no second A. If the answer was `FLAAT`, both As would be yellow.

(I get more issue reports about this than anything else, so maybe I should add a page to the Help that really expands on the precise workings of double letters… The official Wordle works this way, too! — but people can't play enough games there to get an intuition for it, and it also doesn't explain it at all.)

**Comment by final-wave** [comment]
I see. My bad. Thanks for explaining, and sorry to add to the noise.
