### ISSUE TITLE
Word entry/bug?

### ISSUE THREAD

**Issue by YachtSail** [lynn/hello-wordl#72]
I misspelt 'grove' as 'grone', and it was taken as a word. I don't see it in the targets.json list. Bug? 
![0](https://user-images.githubusercontent.com/34665147/151666884-4d4e1c54-2bbe-4198-a924-cf8db75f57c5.jpg)

**Comment by stonedbovines** [comment]
It's in dictionary.json. So, it is an acceptable 'guess' but won't be a final 'answer'
