### ISSUE TITLE
Feature request: include number score (A/Z) with the shared emoji results

### ISSUE THREAD

**Issue by alluringmoon31** [lynn/hello-wordl#90]
To improve readability of shared results, I'd like to request that the generated characters from "Share emoji results" would also include a simple number score in the "A/Z" format, where:

- A = how many guesses it took to get to the solution = 1, 2, 3, 4, 5, 6 or X (for failing)
- Z = the amount of tries available to the player = 6

Thank you for _hello wordl_!

**Comment by lynn** [comment]
That's a good idea! I added it, here's an example:

---

https://hellowordl.net/?challenge=Zmlyc3Q

hello wordl 4/6
⬛🟩⬛⬛🟨
⬛⬛⬛⬛🟨
⬛🟩🟩🟨⬛
🟩🟩🟩🟩🟩
