### ISSUE TITLE
Duplicate letters only receiving a color code on first occurence

### ISSUE THREAD

**Issue by wdbrs** [lynn/hello-wordl#92]
I assume that's the issue, more testing may be needed.  To see it, try this game https://hellowordl.net/?challenge=Z2FsbGJsYWRkZXI, and type in DRAWBRIDGES.  The second R is gray, when the first is yellow.  I would expect them both to be yellow, if neither is in the right place, or for one to be yellow and one green.  One gray should not be possible

**Comment by wdbrs** [comment]
On closer examination, that's not the right explanation.  AQUAMARINES has 3 of the letter A, and the first two are yellow, the third is gray, in the same game linked above.  Still, something is wrong

**Comment by ssaurab** [comment]
The number of times a character is colored in yellow corresponds to its occurrences in the actual word. This is consistent with the actual game [here](https://www.nytimes.com/games/wordle/index.html).

For example: (Contains spoilers)[
[Today's Wordle]](https://user-images.githubusercontent.com/25542635/154779704-ddfe056a-a900-44ed-9779-e7f49b6c0016.png)

**Comment by wdbrs** [comment]
Oh I see. Thanks for the clarification, I'll close this.
